name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        id: script
        with:
          script: |
            var oidc_client = require('@sourav_chanduka/oidc-client')
            try {
            let aud = ''
            const audience = core.getInput('audience', {required: false})
            if (audience !== undefined) 
              aud = `${audience}`
    
            const id_token = await oidc_client.getIDToken(aud)

            core.setOutput('id_token', id_token)

            } catch (error) {
            core.setFailed(error.message)
            }

      - name: get idtoken
        run: echo '${{ steps.script.outputs.id_token }}'
